#################################################
# Makefile for FIMG-3D 
# 2009 (C) Samsung Electronics 
# Author : Jonghun Han <jonghun.han@samsung.com>
#################################################

obj-$(CONFIG_VIDEO_G3D)	+= s3c_g3d.o
