#################################################
# Makefile for FIMG-2D 
# 2009 (C) Samsung Electronics 
# Author : Jonghun Han <jonghun.han@samsung.com>
#################################################

obj-$(CONFIG_VIDEO_G2D)	+= s3c_g2d_driver.o
